extends:
  - '@commitlint/config-conventional'
rules:
  header-max-length: [1, 'always', 72]
  type-enum:
  - 2
  - always
  - - ci
    - feat
    - fix
    - docs
    - style
    - refactor
    - perf
    - test
    - revert
    - chore
    - breaking
    - minor
    - major
help: |
  **Possible types**:
  `ci`:       Changes to our CI configuration files and scripts (example scopes: Travis, Circle CI, BrowserStack, SauceLabs)
  `feat`:     Adds a new feature.
  `fix`:      Solves a bug.
  `docs`:     Adds or alters documentation. (example scopes: readme, worker, code_of_conduct, contributors)
  `style`:    Improves formatting, white-space.
  `refactor`: Rewrites code without feature, performance or bug changes.
  `breaking`: Rewrites code but it brakes backwards compatibility.
  `perf`:     Improves performance.
  `test`:     Adds or modifies tests. (example scopes: functionals, unit-tests)
  `revert`:   Changes that reverting other changes
  `chore`:    No production code change. Updating grunt tasks etc;