[project]
name = "blendernc"
version = "0.8.0"
description = "Extension to load and manipulate geocubes in blender"
authors = [
    {name = "josuemtzmo",email = "josue.mtzmo@gmail.com"}
]
homepage = "https://github.com/blendernc/blendernc"
repository = "https://github.com/blendernc/blendernc"
readme = "README.md"
include = ["LICENSE"]
license = "MIT"
requires-python = ">=3.13"
packages = [
    { include = "blendernc", from = "." },
]
dependencies = [
     "xarray (>=2026.7.0,<2027.0.0)",
    "numpy (>=2.5.2,<3.0.0)",
    "zarr (>=3.3.0,<4.0.0)",
    "ecmwflibs (>=0.7.0,<0.8.0)",
    "cfgrib (>=0.9.15.1,<0.10.0.0)",
    "cmocean (>=4.0.3,<5.0.0)",
    "matplotlib (>=3.11.1,<4.0.0)",
    "dask (>=2026.8.0,<2027.0.0)",
    "scipy (>=1.18.1,<2.0.0)",
    "netcdf4 (>=1.7.4,<2.0.0)",
    "toolz (>=1.1.0,<2.0.0)",
    "pooch (>=1.9.0,<2.0.0)",
    "psutil (>=7.2.2,<8.0.0)",
    "toml (>=0.10.2,<0.11.0)"
]

[tool.poetry.urls]
"Changelog" = "https://github.com/blendernc/blendernc/blob/master/CHANGELOG.md"

[tool.semantic_release]
version_variable = [
    "blendernc/__init__.py:__version__",
    "docs/source/conf.py:release"
]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]

version_pattern= [
    '.github/ISSUE_TEMPLATE.md:BlenderNC Version: {version}',
    # 'blendernc/__init__.py:    "version": (0\d+\,\d+\,\d+)'
]
major_on_zero = false
branch = "master"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
