name: Lint-Flake8

on:
  pull_request:
    paths:
      - '*.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: py-actions/flake8@v1
        with:
          ignore: "F722,F821,E203,W503,F405"
          exclude: "./blendernc/addon_updater*.py"
          max-line-length: "88"
